# Generated by Django 2.0.6 on 2018-07-02 00:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180625_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='date_borrowed',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
