# Generated by Django 2.0.6 on 2018-07-02 05:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0007_auto_20180702_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={},
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='borrower',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='date_borrowed',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='date_returned',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='due_back',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bookinst',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.BookInstance'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_borrowed',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_returned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='remark',
            field=models.TextField(help_text='Condition of the book when returned.', max_length=1000, null=True),
        ),
    ]
