# Generated by Django 2.0.6 on 2018-07-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20180702_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='bookinst',
            new_name='book',
        ),
    ]
