# Generated by Django 2.0.6 on 2018-07-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20180702_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='book',
            new_name='book_instance',
        ),
    ]
