# Generated by Django 2.0.6 on 2018-07-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20180702_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='remark',
            field=models.TextField(blank=True, help_text='Condition of the book when returned.', max_length=1000, null=True),
        ),
    ]
