# Generated by Django 2.0.6 on 2018-07-12 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20180711_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('view_author_detail', 'Can view author detail'),)},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('view_book_detail', 'Can view book detail'),)},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('view_transactions', 'Can view transactions'), ('view_transactions_by_user', 'Can view transactions by current user'))},
        ),
    ]
