# Generated by Django 2.0.6 on 2018-07-24 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20180712_1152'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': (('view_transactions_by_user', 'Can view transactions by current user'), ('view_transactions', 'Can view transactions'))},
        ),
    ]
